import type { SkillManifest } from "./types";

const timestamp = "2026-07-31T00:00:00.000Z";

export const BUILTIN_SKILLS: SkillManifest[] = [
  {
    id: "core-agent",
    name: "Core Agent",
    description: "基础推理、时间查询、计算与长期记忆能力。",
    version: "1.0.0",
    triggers: [],
    prompt: "Keep reasoning concise. Use recalled memory only when relevant. Save durable user preferences or facts only when explicitly requested or clearly stable.",
    allowedTools: ["get_time", "run_js", "memory_search", "memory_save"],
    enabled: true,
    builtin: true,
    always: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "github-research",
    name: "GitHub Research",
    description: "查询 GitHub 仓库、版本、tag、release 和项目元数据。",
    version: "1.0.0",
    triggers: ["github", "仓库", "repo", "repository", "release", "版本", "tag", "开源项目"],
    prompt: "For GitHub facts, prefer github_search. Distinguish GitHub Releases from repository tags and cite the repository URL.",
    allowedTools: ["github_search", "fetch_url", "render_mermaid", "memory_save"],
    enabled: true,
    builtin: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "web-research",
    name: "Web Research",
    description: "网页搜索、正文抓取与来源归纳。",
    version: "1.0.0",
    triggers: ["搜索", "查找", "网页", "新闻", "资料", "search", "website", "latest", "最新"],
    prompt: "Search first, fetch only the most relevant sources, then synthesize. Never keep retrying an unavailable provider.",
    allowedTools: ["web_search", "fetch_url", "github_search", "memory_save"],
    enabled: true,
    builtin: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "data-analysis",
    name: "Data Analysis",
    description: "使用 JavaScript 做确定性计算、数据转换和校验。",
    version: "1.0.0",
    triggers: ["计算", "统计", "分析", "转换", "多少", "calculate", "analysis", "statistics", "json"],
    prompt: "Use run_js for calculations instead of mental arithmetic. Return the computed value and explain assumptions briefly.",
    allowedTools: ["run_js", "get_time", "render_mermaid", "memory_save"],
    enabled: true,
    builtin: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "diagramming",
    name: "Diagramming",
    description: "把流程、架构和时序关系渲染为 Mermaid 图。",
    version: "1.0.0",
    triggers: ["图", "流程", "架构", "时序", "mermaid", "diagram", "flowchart", "sequence"],
    prompt: "When a diagram improves clarity, call render_mermaid with valid Mermaid syntax and also provide a short textual explanation.",
    allowedTools: ["render_mermaid", "run_js"],
    enabled: true,
    builtin: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];
